// src/components/footer.svelte
<footer class="border-t border-gray-200 bg-white dark:border-white/10 dark:bg-[rgb(20,20,20)]">
	<div class="mx-auto max-w-7xl px-6 py-12 lg:px-8">
		<!-- Main footer content -->
		<div class="xl:grid xl:grid-cols-3 xl:gap-8">
			<!-- Logo and tagline -->
			<div class="space-y-4">
				<div class="flex items-center gap-3">
					<a href="/" class="inline-block">
						<img src="/logos/cloudproud/icon-light.svg" alt="Cloud Proud" class="h-8 dark:hidden" />
						<img
							src="/logos/cloudproud/icon-dark.svg"
							alt="Cloud Proud"
							class="hidden h-8 dark:block"
						/>
					</a>
					<!-- Team member Kippa -->
					<div class="relative group">
						<img
							src="/team/kippa.jpeg"
							alt="Kippa - Team Member"
							class="w-10 h-10 rounded-full object-cover hover:shadow-[0_0_20px_rgba(34,211,238,0.7)] transition-all duration-300"
						/>
						<div
							class="absolute top-full left-1/2 -translate-x-1/2 mt-3 px-3 py-2 bg-gray-900/95 dark:bg-white/95 backdrop-blur-sm rounded-lg shadow-xl opacity-0 group-hover:opacity-100 transition-all duration-200 pointer-events-none z-10"
						>
							<div class="text-sm font-medium text-white dark:text-gray-900 whitespace-nowrap">
								Kippa
							</div>
							<div class="text-xs text-gray-400 dark:text-gray-500 whitespace-nowrap">
								Head of Security
							</div>
							<div
								class="absolute -top-1.5 left-1/2 -translate-x-1/2 w-3 h-3 bg-gray-900/95 dark:bg-white/95 rotate-45"
							></div>
						</div>
					</div>
				</div>
				<p class="text-sm/6 text-gray-600 dark:text-gray-400 max-w-xs">
					Innovative cloud solutions and smart software for businesses ready to lead in the digital
					world.
				</p>
			</div>

			<!-- Navigation columns -->
			<div class="mt-16 grid grid-cols-2 gap-8 xl:col-span-2 xl:mt-0">
				<div>
					<h3 class="text-sm font-semibold text-gray-900 dark:text-white">Company</h3>
					<ul role="list" class="mt-6 space-y-4">
						<li>
							<a
								href="https://cal.com/jeroenrinzema/introduction"
								class="text-sm/6 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
							>
								Contact
							</a>
						</li>
						<li>
							<a
								href="https://www.meetup.com/dev-pulse/"
								class="text-sm/6 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
							>
								DevPulse Meetup
							</a>
						</li>
					</ul>
				</div>
				<div>
					<h3 class="text-sm font-semibold text-gray-900 dark:text-white">Resources</h3>
					<ul role="list" class="mt-6 space-y-4">
						<li>
							<a
								href="https://github.com/cloudproud"
								class="text-sm/6 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
							>
								GitHub
							</a>
						</li>
						<li>
							<a
								href="https://www.linkedin.com/company/cloudproud"
								class="text-sm/6 text-gray-600 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white transition-colors"
							>
								LinkedIn
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>

		<!-- Bottom bar -->
		<div class="mt-12 border-t border-gray-200 pt-8 dark:border-white/10">
			<div class="flex flex-col items-center justify-between gap-4 sm:flex-row">
				<!-- Copyright -->
				<p class="text-sm/6 text-gray-500 dark:text-gray-400">
					&copy; {new Date().getFullYear()} Cloud Proud B.V. All rights reserved.
				</p>

				<!-- Social links and EU badge -->
				<div class="flex items-center gap-6">
					<!-- Social icons -->
					<div class="flex gap-4">
						<a
							href="https://github.com/cloudproud"
							class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-white transition-colors"
							aria-label="GitHub"
						>
							<svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" class="size-5">
								<path
									d="M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z"
									clip-rule="evenodd"
									fill-rule="evenodd"
								/>
							</svg>
						</a>
						<a
							href="https://www.linkedin.com/company/cloudproud"
							class="text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-white transition-colors"
							aria-label="LinkedIn"
						>
							<svg fill="currentColor" class="size-5" aria-hidden="true" viewBox="0 0 24 24">
								<path
									d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"
								/>
							</svg>
						</a>
					</div>

					<!-- EU Badge -->
					<span class="inline-flex items-center gap-1.5 text-sm text-gray-500 dark:text-gray-400">
						🇳🇱🇪🇺 Proudly built in the Netherlands
					</span>
				</div>
			</div>
		</div>
	</div>
</footer>

// components/Footer.vue
<template>
  <footer class="bg-gray-900" aria-labelledby="footer-heading" id="footer">
    <h2 id="footer-heading" class="sr-only">Footer</h2>
    <div class="mx-auto max-w-7xl px-6 pb-8">
      <div class="pt-8 md:flex md:items-center md:justify-between">
        <div class="flex space-x-6 md:order-2">
          <a v-for="item in navigation.social" :key="item.name" :href="item.href" class="text-gray-500 hover:text-gray-400">
            <span class="sr-only">{{ item.name }}</span>
            <component :is="item.icon" class="h-6 w-6" aria-hidden="true" />
          </a>
        </div>
        <p class="mt-8 text-xs leading-5 text-gray-400 md:order-1 md:mt-0">&copy; {{ new Date().getFullYear() }} Cloud Proud, B.V. All rights reserved.</p>
      </div>
    </div>
  </footer>
</template>

<script setup>
import { defineComponent, h } from 'vue'

const navigation = {
  solutions: [
    { name: 'Marketing', href: '#' },
    { name: 'Analytics', href: '#' },
    { name: 'Commerce', href: '#' },
    { name: 'Insights', href: '#' },
  ],
  support: [
    { name: 'Pricing', href: '#' },
    { name: 'Documentation', href: '#' },
    { name: 'Guides', href: '#' },
    { name: 'API Status', href: '#' },
  ],
  company: [
    { name: 'About', href: '#' },
    { name: 'Blog', href: '#' },
    { name: 'Jobs', href: '#' },
    { name: 'Press', href: '#' },
    { name: 'Partners', href: '#' },
  ],
  legal: [
    { name: 'Claim', href: '#' },
    { name: 'Privacy', href: '#' },
    { name: 'Terms', href: '#' },
  ],
  social: [
    {
      name: 'GitHub',
      href: 'https://github.com/cloudproud/',
      icon: defineComponent({
        render: () =>
          h('svg', { fill: 'currentColor', viewBox: '0 0 24 24' }, [
            h('path', {
              'fill-rule': 'evenodd',
              d: 'M12 2C6.477 2 2 6.484 2 12.017c0 4.425 2.865 8.18 6.839 9.504.5.092.682-.217.682-.483 0-.237-.008-.868-.013-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.029-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.379.202 2.398.1 2.651.64.7 1.028 1.595 1.028 2.688 0 3.848-2.339 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.019 10.019 0 0022 12.017C22 6.484 17.522 2 12 2z',
              'clip-rule': 'evenodd',
            }),
          ]),
      }),
    },
    {
      name: 'YouTube',
      href: 'https://www.youtube.com/@CloudProudBV',
      icon: defineComponent({
        render: () =>
          h('svg', { fill: 'currentColor', viewBox: '0 0 24 24' }, [
            h('path', {
              'fill-rule': 'evenodd',
              d: 'M19.812 5.418c.861.23 1.538.907 1.768 1.768C21.998 8.746 22 12 22 12s0 3.255-.418 4.814a2.504 2.504 0 0 1-1.768 1.768c-1.56.419-7.814.419-7.814.419s-6.255 0-7.814-.419a2.505 2.505 0 0 1-1.768-1.768C2 15.255 2 12 2 12s0-3.255.417-4.814a2.507 2.507 0 0 1 1.768-1.768C5.744 5 11.998 5 11.998 5s6.255 0 7.814.418ZM15.194 12 10 15V9l5.194 3Z',
              'clip-rule': 'evenodd',
            }),
          ]),
      }),
    },
    {
      name: 'Linkedin',
      href: 'https://www.linkedin.com/company/cloudproud',
      icon: defineComponent({
        render: () =>
          h('svg', { fill: 'currentColor', viewBox: '0 0 24 24' }, [
            h('path', {
              'fill-rule': 'evenodd',
              d: 'M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z',
              'clip-rule': 'evenodd',
            }),
          ]),
      }),
    },
  ],
}
</script>
